server:
  port: 9013
spring:
  application:
    name: tensquare-encrypt
zuul:
  routes:
    tensquare-article: #文章
      path: /article/** #配置请求URL的请求规则
      serviceId: tensquare-article #指定Eureka注册中心中的服务id
      strip-prefix: true #所有的article的请求都进行转发
      sentiviteHeaders:
        customSensitiveHeaders: true  #让zuul网关处理cookie和重定向
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true